{
 "title": "Motor M-01 - Monitoreo en vivo",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperatura (C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"lecturas_motor\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"lecturas_motor\") |> filter(fn: (r) => r.equipo_id == \"motor_001\") |> filter(fn: (r) => r.variable == \"temperatura\") |> filter(fn: (r) => r._field == \"valor\")"
    }
   ]
  },
  {
   "title": "Corriente (A)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"lecturas_motor\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"lecturas_motor\") |> filter(fn: (r) => r.equipo_id == \"motor_001\") |> filter(fn: (r) => r.variable == \"corriente\") |> filter(fn: (r) => r._field == \"valor\")"
    }
   ]
  },
  {
   "title": "Vibracion (mm/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "query": "from(bucket: \"lecturas_motor\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"lecturas_motor\") |> filter(fn: (r) => r.equipo_id == \"motor_001\") |> filter(fn: (r) => r.variable == \"vibracion\") |> filter(fn: (r) => r._field == \"valor\")"
    }
   ]
  }
 ]
}